// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgdEOyErgQQBCtoLdqtY7zPh4ALWFxUBU',
    appId: '1:945981272799:web:55c34575612d57b4a9af6a',
    messagingSenderId: '945981272799',
    projectId: 'society-management-56e43',
    authDomain: 'society-management-56e43.firebaseapp.com',
    storageBucket: 'society-management-56e43.firebasestorage.app',
    measurementId: 'G-N2FTTRNE98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChD-xuOcNyktKE4V-R_PH5eCwi583tcTU',
    appId: '1:945981272799:android:5f79f659712fa7b8a9af6a',
    messagingSenderId: '945981272799',
    projectId: 'society-management-56e43',
    storageBucket: 'society-management-56e43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2srdNqrMxUA7oNbRBIH8rGwhULwUvsZs',
    appId: '1:945981272799:ios:c40f87637ec9eee3a9af6a',
    messagingSenderId: '945981272799',
    projectId: 'society-management-56e43',
    storageBucket: 'society-management-56e43.firebasestorage.app',
    iosBundleId: 'com.example.societyManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2srdNqrMxUA7oNbRBIH8rGwhULwUvsZs',
    appId: '1:945981272799:ios:c40f87637ec9eee3a9af6a',
    messagingSenderId: '945981272799',
    projectId: 'society-management-56e43',
    storageBucket: 'society-management-56e43.firebasestorage.app',
    iosBundleId: 'com.example.societyManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgdEOyErgQQBCtoLdqtY7zPh4ALWFxUBU',
    appId: '1:945981272799:web:c260cedd3cf749b0a9af6a',
    messagingSenderId: '945981272799',
    projectId: 'society-management-56e43',
    authDomain: 'society-management-56e43.firebaseapp.com',
    storageBucket: 'society-management-56e43.firebasestorage.app',
    measurementId: 'G-H20W19GKMV',
  );
}
